# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from tkinter import *
from PIL import Image,ImageTk
import os
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 640)
        MainWindow.setFixedSize(805,640)
        MainWindow.setStyleSheet('background-color:skyblue')
        MainWindow.setWindowIcon(QtGui.QIcon("img.ico"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 781, 601))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 20, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 20, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 120, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 231, 231))
        self.label_7.setObjectName("textBrowser")
        self.label_7.setStyleSheet('background-color:white')
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(105)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 170, 231, 231))
        self.label_8.setObjectName("textBrowser_2")
        self.label_8.setStyleSheet('background-color:white')
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(105)
        self.label_8.setFont(font)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 120, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 440, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 430, 651, 51))
        self.textEdit_2.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 520, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 520, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 520, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.add)
        self.pushButton_2.clicked.connect(self.convert)
        self.pushButton_3.clicked.connect(self.savefile)
        self.pushButton_4.clicked.connect(self.cl)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def add(self):
        self.cl()
        global name,ext,i,x,b,f
        f=False
        x = QFileDialog.getOpenFileName(filter="Image files (*.jpg *.png *.ico *.apng *.avif *.gif *.svg *.webp *.bmp *.tif *.jfif)")
        p=x[0].split('/')
        b=''
        p.remove(p[-1])
        for i in p:
            b += str(i)+'/'
        self.textEdit.setPlainText(x[0])
        self.textEdit.setReadOnly(True)
        name,ext=os.path.splitext((x[0].split("/"))[-1])
        if name:
            i = QtGui.QPixmap(x[0])
            if i.width() >231 or i.height()>231:
                i=i.scaled(231,231,QtCore.Qt.KeepAspectRatio)
            self.label_7.setPixmap(i)
            self.label_8.setText('Image Available\n to convert.')
            self.textEdit_2.setPlainText("Image selected!!")
            f=True
        else:
            pass
    def cl(self):
        global f
        self.textEdit.setPlainText("")
        self.textEdit_2.setPlainText("")
        self.label_7.setText("No Image \n Available!")
        self.label_8.setText('Nothing to \n convert!')
        f=False
    def convert(self):
        global v,c
        c=self.comboBox.currentText()
        if f:
            if name:
                if c==ext:
                    self.textEdit_2.setPlainText("Same format choose another format!!")
                else:
                    try:
                        if c=='.ico':
                            v=Image.open(x[0]).convert('RGBA')
                        else:
                            v=Image.open(x[0]).convert('RGB')
                        self.textEdit_2.setPlainText('Converted Successfully!')
                    except:
                        self.textEdit_2.setPlainText('Invalid Conversion!!')
            else:
                self.textEdit_2.setPlainText('Please select an Image!')
        else:
            pass
    def savefile(self):
        global f
        if f:
            try:
                v.save(b+name+c)
                self.label_8.setPixmap(QtGui.QPixmap(b+name+ext))
                self.textEdit_2.setPlainText('Saved Successfully!')
                f=False
            except:
                self.textEdit_2.setPlainText("Invalid File type!!")
        else:
            pass
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Format Convertor"))
        self.label_2.setText(_translate("MainWindow", "Select Image:"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.label_3.setText(_translate("MainWindow", "Opened Image:"))
        self.label_4.setText(_translate("MainWindow", "Converted Image:"))
        self.label_5.setText(_translate("MainWindow", "Choose Format:"))
        self.label_7.setText(_translate("MainWindow", "No Image\n Available."))
        self.label_8.setText(_translate("MainWindow", "Nothing To\n Convert!!"))
        self.comboBox.setItemText(0, _translate("MainWindow", ".apng"))
        self.comboBox.setItemText(1, _translate("MainWindow", ".avif"))
        self.comboBox.setItemText(2, _translate("MainWindow", ".gif"))
        self.comboBox.setItemText(3, _translate("MainWindow", ".jpg"))
        self.comboBox.setItemText(4, _translate("MainWindow", ".png"))
        self.comboBox.setItemText(5, _translate("MainWindow", ".svg"))
        self.comboBox.setItemText(6, _translate("MainWindow", ".webp"))
        self.comboBox.setItemText(7, _translate("MainWindow", ".bmp"))
        self.comboBox.setItemText(8, _translate("MainWindow", ".ico"))
        self.comboBox.setItemText(9, _translate("MainWindow", ".tif"))
        self.comboBox.setItemText(9, _translate("MainWindow", ".jfif"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.pushButton_2.setText(_translate("MainWindow", "Convert"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
