print("     R R R R ")
print("     R      R")
print("     R      R")
print("     R R R   ")
print("     R   R   ")
print("     R      R")
print("        A    ")
print("      A   A  ")
print("    A       A")
print("   A A A A A A")
print("  A           A")
print("  A           A")